
# This file is automatically generated, you probably don't want to edit this

LaSARSmodelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LaSARSmodelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            subscale = NULL,
            subject = NULL,
            direction = NULL,
            rev_label = "",
            estDirectPref = TRUE,
            resp_opts = 5,
            ls_plot = FALSE,
            subj_est_table = FALSE,
            get_subj_ests = FALSE, ...) {

            super$initialize(
                package="LaSARS",
                name="LaSARSmodel",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response)
            private$..subscale <- jmvcore::OptionVariable$new(
                "subscale",
                subscale)
            private$..subject <- jmvcore::OptionVariable$new(
                "subject",
                subject)
            private$..direction <- jmvcore::OptionVariable$new(
                "direction",
                direction)
            private$..rev_label <- jmvcore::OptionString$new(
                "rev_label",
                rev_label,
                default="")
            private$..estDirectPref <- jmvcore::OptionBool$new(
                "estDirectPref",
                estDirectPref,
                default=TRUE)
            private$..resp_opts <- jmvcore::OptionInteger$new(
                "resp_opts",
                resp_opts,
                default=5,
                max=30,
                min=2)
            private$..ls_plot <- jmvcore::OptionBool$new(
                "ls_plot",
                ls_plot,
                default=FALSE)
            private$..subj_est_table <- jmvcore::OptionBool$new(
                "subj_est_table",
                subj_est_table,
                default=FALSE)
            private$..get_subj_ests <- jmvcore::OptionAction$new(
                "get_subj_ests",
                get_subj_ests,
                action="open")

            self$.addOption(private$..response)
            self$.addOption(private$..subscale)
            self$.addOption(private$..subject)
            self$.addOption(private$..direction)
            self$.addOption(private$..rev_label)
            self$.addOption(private$..estDirectPref)
            self$.addOption(private$..resp_opts)
            self$.addOption(private$..ls_plot)
            self$.addOption(private$..subj_est_table)
            self$.addOption(private$..get_subj_ests)
        }),
    active = list(
        response = function() private$..response$value,
        subscale = function() private$..subscale$value,
        subject = function() private$..subject$value,
        direction = function() private$..direction$value,
        rev_label = function() private$..rev_label$value,
        estDirectPref = function() private$..estDirectPref$value,
        resp_opts = function() private$..resp_opts$value,
        ls_plot = function() private$..ls_plot$value,
        subj_est_table = function() private$..subj_est_table$value,
        get_subj_ests = function() private$..get_subj_ests$value),
    private = list(
        ..response = NA,
        ..subscale = NA,
        ..subject = NA,
        ..direction = NA,
        ..rev_label = NA,
        ..estDirectPref = NA,
        ..resp_opts = NA,
        ..ls_plot = NA,
        ..subj_est_table = NA,
        ..get_subj_ests = NA)
)

LaSARSmodelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LaSARSmodelResults",
    inherit = jmvcore::Group,
    active = list(
        mu_desc = function() private$.items[["mu_desc"]],
        rs_desc = function() private$.items[["rs_desc"]],
        pairs_plot = function() private$.items[["pairs_plot"]],
        resultsTable = function() private$.items[["resultsTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent State and Response Style")
            self$add(jmvcore::Table$new(
                options=options,
                name="mu_desc",
                title="Latent State Descriptives",
                visible=TRUE,
                rows="",
                clearWith=list(
                    "response",
                    "subscale",
                    "direction",
                    "subject",
                    "resp_opts",
                    "estDirectPref",
                    "rev_label"),
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="med", 
                        `title`="Median", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rs_desc",
                title="Response Syle Descriptives",
                visible=TRUE,
                rows="",
                clearWith=list(
                    "response",
                    "subscale",
                    "direction",
                    "subject",
                    "resp_opts",
                    "estDirectPref",
                    "rev_label"),
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="med", 
                        `title`="Median", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="pairs_plot",
                title="De-Biased Latent State Correlations",
                visible=FALSE,
                width=500,
                height=500,
                renderFun=".pairsplot",
                refs=list(
                    "GGally",
                    "ggplot2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTable",
                title="Subject\u2011level Results",
                rows="all",
                columns=list(),
                visible=FALSE,
                clearWith=list(
                    "subject",
                    "response",
                    "subscale",
                    "direction",
                    "rev_label",
                    "estDirectPref",
                    "resp_opts")))}))

LaSARSmodelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LaSARSmodelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "LaSARS",
                name = "LaSARSmodel",
                version = c(1,0,0),
                options = options,
                results = LaSARSmodelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Latent State and Response Style
#'
#' 
#' @param data .
#' @param response .
#' @param subscale .
#' @param subject .
#' @param direction .
#' @param rev_label .
#' @param estDirectPref .
#' @param resp_opts .
#' @param ls_plot .
#' @param subj_est_table .
#' @param get_subj_ests .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mu_desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rs_desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairs_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$resultsTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mu_desc$asDF}
#'
#' \code{as.data.frame(results$mu_desc)}
#'
#' @export
LaSARSmodel <- function(
    data,
    response,
    subscale,
    subject,
    direction,
    rev_label = "",
    estDirectPref = TRUE,
    resp_opts = 5,
    ls_plot = FALSE,
    subj_est_table = FALSE,
    get_subj_ests = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("LaSARSmodel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(subscale)) subscale <- jmvcore::resolveQuo(jmvcore::enquo(subscale))
    if ( ! missing(subject)) subject <- jmvcore::resolveQuo(jmvcore::enquo(subject))
    if ( ! missing(direction)) direction <- jmvcore::resolveQuo(jmvcore::enquo(direction))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(subscale), subscale, NULL),
            `if`( ! missing(subject), subject, NULL),
            `if`( ! missing(direction), direction, NULL))


    options <- LaSARSmodelOptions$new(
        response = response,
        subscale = subscale,
        subject = subject,
        direction = direction,
        rev_label = rev_label,
        estDirectPref = estDirectPref,
        resp_opts = resp_opts,
        ls_plot = ls_plot,
        subj_est_table = subj_est_table,
        get_subj_ests = get_subj_ests)

    analysis <- LaSARSmodelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

